### ISSUE TITLE
Add luarocks package in docker image

### ISSUE THREAD

**Issue by ErwinSteffens** [3scale/apicast#320]
We're trying to add Let's encrypt to our custom docker image. We are creating a new docker image based on the apicast docker image. Some custom configurations and scripts are added in the new image. Now we want to add Let's Encrypt by using the [lua-resty-auto-ssl](https://github.com/GUI/lua-resty-auto-ssl) package.

We're not very familiar with Lua, OpenResty or Luarocks. Now we're trying to add a package to the apicast luarocks file and get it installed in the correct place, but without success. Can you help us getting forward?

**Comment by mikz** [comment]
Very interesting use case. I'll try to come up with an example.

**Comment by ErwinSteffens** [comment]
Ok, thanks. Where can we find the Dockerfile you're using for publishing the images? I think it isn't in the repo.

**Comment by mikz** [comment]
Yep. We are using [s2i](https://github.com/openshift/source-to-image) to build the image.
There is [an example](https://github.com/3scale/apicast/blob/master/examples/s2i/README.md) of how to use it to extend the image with custom files.

The base image is https://github.com/3scale/s2i-openresty and we aim to have general source-to-image builder for openresty applications. So your use case is totally in line with what we want to do.

We install all rockspec files added to the image are used to install dependencies. So adding some extra could work. But I haven't tried it so I'll need to verify it by making an example.

**Comment by ErwinSteffens** [comment]
Got it fixed for now. Adding `--tree` to the luarocks install command solved it. I think it would be better to use the s2i setup you are proposing so we can fix the version in a luarocks file. When we have a good example we can try it out.

This is our Dockerfile:

```Dockerfile
FROM quay.io/3scale/apicast:master

USER root

ENV THREESCALE_CONFIG_FILE=/opt/app/config.json
ENV APICAST_MODULE=custom-module

WORKDIR /opt/app

COPY src /opt/app/

RUN luarocks install lua-resty-auto-ssl --tree /usr/local/openresty/luajit

USER default
```

**Comment by mikz** [comment]
You can try WIP #327. I pushed it as http://quay.io/3scale/apicast:s2i. You shouldn't even need a Dockerfile as you can add files and change ENV easily with s2i.

**Comment by ErwinSteffens** [comment]
Ok, thanks. Will try it out later this week (have some pressure to get the sprint done now ;-) ).

**Comment by mikz** [comment]
There is one slight issue with this. The released image does not contain luarocks. 
There are two kinds of images: builder and runtime. Builder has dependencies like luarocks and compiler. Runtime has just openresty to run everything, but no tools to install anything.

For using s2i for modifications the builder image has to be used. I'll make sure we push it to quay along with the runtime image.

**Comment by ErwinSteffens** [comment]
Ok, but somehow the luarocks step succeeds. Can you indicate when you have
pushed this image and provide a sample?

Nginx now crashes during the requesting of a certificate. Could be due to
missing dependencies maybe.

Offtopic: Do you have some ETA on the new request containing the Keycloak
integration?

2017-03-22 10:45 GMT+01:00 Michal Cichra <notifications@github.com>:

**Comment by ErwinSteffens** [comment]
I've got the build with s2i running. Great tool, thanks!

The auto-ssl process still crashes when enabled. 
```
2017/03/22 20:57:12 [alert] 1#1: worker process 104 exited on signal 11 (core dumped)
```

I'll try to figure it out. More an issue for the auto-ssl library. 

Thanks!

**Comment by mikz** [comment]
I had similar issues with newrelic when I was missing some shared library. It is possible that some package is missing, but then s2i wouldn't help because it does not run as root and normal Docker build would have to be used. But then you could continue with s2i. 

22. 3. 2017 v 22:02, Erwin Steffens <notifications@github.com>:

**Comment by ErwinSteffens** [comment]
It has a depedency op OpenSsl `1.0.2e` but the image contains `1.0.1e`. Could upgrade this and test if it works. Yum says `1.0.1e` is latest version so need to figure out how to do this.

**Comment by mikz** [comment]
Uf. Thats unfortunate. That means you have to rebuild OpenResty from source including OpenSSL. 
CentOS packages are using whatever is in CentOS and I guess that is not going to move to 1.0.2 as that would require rebuild of every other package.

**Comment by ErwinSteffens** [comment]
Ok, that's too much work for now. I think we will buy some certs for now.

**Comment by ErwinSteffens** [comment]
When I update and rebuild openresty with these steps: https://github.com/GUI/lua-resty-auto-ssl/issues/40. Do you think this will be enough?

Can give it a try when we have some spare time.

**Comment by mikz** [comment]
Ah! Looks like openresty packages already provide own compiled OpenSSL: https://openresty.org/en/rpm-packages.html#openresty-openssl

So just installing that one should do the trick. I'll try to incorporate this into the main build.

**Comment by mikz** [comment]
@ErwinSteffens latest master should now include OpenSSL 1.0.2.

**Comment by ErwinSteffens** [comment]
Ok thanks, I'll give a try next week.

**Comment by ErwinSteffens** [comment]
@mikz When I build the image it still contains v1.0.1:
```
bash-4.2$ openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
```

**Comment by ErwinSteffens** [comment]
Runnings these commands:
```
C:\Work\Projects\SDF\apicast [master]> docker pull quay.io/3scale/apicast:master
master: Pulling from 3scale/apicast
785fe1d06b2d: Already exists
de8ccc4472a6: Already exists
ff3645ffe1bb: Already exists
e0365316ba4a: Already exists
cb89fee9e475: Already exists
c91cec682347: Already exists
Digest: sha256:5940a8fea52b04e308f2eef5b9ec8ef0abd8c1cb1f6b7eb57b2ca949405c0828
Status: Image is up to date for quay.io/3scale/apicast:master
C:\Work\Projects\SDF\apicast [master]> docker pull quay.io/3scale/apicast:master-builder
master-builder: Pulling from 3scale/apicast
45a2e645736c: Already exists
734fb161cf89: Already exists
78efc9e155c4: Already exists
8a3400b7e31a: Already exists
fda7c507da8e: Already exists
1e064830e8a7: Already exists
713dd038fda6: Already exists
8143cf324af3: Already exists
3e93ce490f10: Already exists
158a792ccbec: Already exists
Digest: sha256:00eba7b6e66e8678d7112284554f3516e0bc58f142b97867e43d405aac3c5408
Status: Image is up to date for quay.io/3scale/apicast:master-builder
C:\Work\Projects\SDF\apicast\src [master]> s2i build . quay.io/3scale/apicast:master-builder apicast-custom:latest
---> Installing application source...
---> Building application from source...

Missing dependencies for apicast-customization:
lua-resty-auto-ssl == 0.10.5-1

mkdir -p /tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/build
rm -f /tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/build/stamp-dehydrated-*
curl -sSLo /tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/lib/resty/auto-ssl/vendor/dehydrated "https://raw.githubusercontent.com/lukas2511/dehydrated/v0.3.1/dehydrated"
chmod +x /tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/lib/resty/auto-ssl/vendor/dehydrated
touch /tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/build/stamp-dehydrated-v0.3.1
rm -f /tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/build/stamp-lua-resty-shell-*
curl -sSLo /tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/lib/resty/auto-ssl/vendor/shell.lua "https://raw.githubusercontent.com/juce/lua-resty-shell/955243d70506c21e7cc29f61d745d1a8a718994f/lib/resty/shell.lua"
touch /tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/build/stamp-lua-resty-shell-955243d70506c21e7cc29f61d745d1a8a718994f
rm -f /tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/build/stamp-sockproc-*
cd /tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/build && curl -sSLo sockproc-fc8ad3f15a7b2cf2eaf39663b90010efc55e207c.tar.gz "https://github.com/juce/sockproc/archive/fc8ad3f15a7b2cf2eaf39663b90010efc55e207c.tar.gz"
cd /tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/build && tar -xf sockproc-fc8ad3f15a7b2cf2eaf39663b90010efc55e207c.tar.gz
cd /tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/build/sockproc-fc8ad3f15a7b2cf2eaf39663b90010efc55e207c && make
make[1]: Entering directory `/tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/build/sockproc-fc8ad3f15a7b2cf2eaf39663b90010efc55e207c'
gcc -Wall -Werror -o sockproc sockproc.c
make[1]: Leaving directory `/tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/build/sockproc-fc8ad3f15a7b2cf2eaf39663b90010efc55e207c'
cp /tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/build/sockproc-fc8ad3f15a7b2cf2eaf39663b90010efc55e207c/sockproc /tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/lib/resty/auto-ssl/vendor/sockproc
chmod +x /tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/lib/resty/auto-ssl/vendor/sockproc
touch /tmp/luarocks_lua-resty-auto-ssl-0.10.5-1-685/lua-resty-auto-ssl/build/stamp-sockproc-fc8ad3f15a7b2cf2eaf39663b90010efc55e207c
install -d /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl
install -m 644 lib/resty/auto-ssl.lua /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl.lua
install -m 644 lib/resty/auto-ssl/init_master.lua /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/init_master.lua
install -m 644 lib/resty/auto-ssl/init_worker.lua /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/init_worker.lua
install -d /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/jobs
install -m 644 lib/resty/auto-ssl/jobs/renewal.lua /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/jobs/renewal.lua
install -d /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/servers
install -m 644 lib/resty/auto-ssl/servers/challenge.lua /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/servers/challenge.lua
install -m 644 lib/resty/auto-ssl/servers/hook.lua /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/servers/hook.lua
install -d /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/shell
install -m 755 lib/resty/auto-ssl/shell/letsencrypt_hooks /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/shell/letsencrypt_hooks
install -m 755 lib/resty/auto-ssl/shell/start_sockproc /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/shell/start_sockproc
install -m 644 lib/resty/auto-ssl/ssl_certificate.lua /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/ssl_certificate.lua
install -d /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/ssl_providers
install -m 644 lib/resty/auto-ssl/ssl_providers/lets_encrypt.lua /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/ssl_providers/lets_encrypt.lua
install -m 644 lib/resty/auto-ssl/storage.lua /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/storage.lua
install -d /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/storage_adapters
install -m 644 lib/resty/auto-ssl/storage_adapters/file.lua /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/storage_adapters/file.lua
install -m 644 lib/resty/auto-ssl/storage_adapters/redis.lua /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/storage_adapters/redis.lua
install -d /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/utils
install -m 644 lib/resty/auto-ssl/utils/shell_execute.lua /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/utils/shell_execute.lua
install -m 644 lib/resty/auto-ssl/utils/start_sockproc.lua /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/utils/start_sockproc.lua
install -m 644 lib/resty/auto-ssl/utils/run_command.lua /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/utils/run_command.lua
install -d /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/vendor
install -m 755 lib/resty/auto-ssl/vendor/dehydrated /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/vendor/dehydrated
install -m 644 lib/resty/auto-ssl/vendor/shell.lua /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/vendor/shell.lua
install -m 755 lib/resty/auto-ssl/vendor/sockproc /usr/local/openresty/luajit/lib64/luarocks/rocks/lua-resty-auto-ssl/0.10.5-1/lua/resty/auto-ssl/vendor/sockproc
Using https://luarocks.org/lua-resty-auto-ssl-0.10.5-1.src.rock... switching to 'build' mode
Updating manifest for /usr/local/openresty/luajit/lib64/luarocks/rocks
lua-resty-auto-ssl 0.10.5-1 is now built and installed in /usr/local/openresty/luajit (license: MIT)

Updating manifest for /usr/local/openresty/luajit/lib64/luarocks/rocks
apicast-customization 0.1-1 is now built and installed in /usr/local/openresty/luajit

Updating manifest for /usr/local/openresty/luajit/lib64/luarocks/rocks
apicast 0.1-0 is now built and installed in /usr/local/openresty/luajit

warning: Failed to kill container "cbdf1ccb89c1d463cabc06dfdb68fa1a545f768b2e11e0314c45f0360a488236": Error response from daemon: {"message":"Cannot kill container cbdf1ccb89c1d463cabc06dfdb68fa1a545f768b2e11e0314c45f0360a488236: Container cbdf1ccb89c1d463cabc06dfdb68fa1a545f768b2e11e0314c45f0360a488236 is not running"}
C:\Work\Projects\SDF\apicast\src [master]> docker images
REPOSITORY                                                  TAG                                        IMAGE ID            CREATED             SIZE
apicast-custom                                              latest                                     5f0ef310d2f7        36 seconds ago      496 MB
quay.io/3scale/apicast                                      master-builder                             20092b2b55a6        About an hour ago   495 MB
quay.io/3scale/apicast                                      master                                     5b110b0d6048        About an hour ago   267 MB
C:\Work\Projects\apicast\src [master]>
C:\Work\Projects\apicast\src [master]>
C:\Work\Projects\apicast\src [master]> docker run -it --rm apicast-custom:latest bash
bash-4.2$ openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
bash-4.2$
```

**Comment by mikz** [comment]
You can check the OpenSSL OpenResty was compiled with via `openresty -V`. It does not have to be the same as available on the system as the binary. I'll try to make example image containing working lua-resty-auto-ssl soon.

**Comment by ErwinSteffens** [comment]
Ah, ok. Output is:

```
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)
built with OpenSSL 1.0.2j  26 Sep 2016 (running with OpenSSL 1.0.2k  26 Jan 2017)
```

So this should be ok. I thought the OpenSSL version should probably be trigger the error, but I still get it when we add the autossl process:
```
19-4-2017 06:49:242017/04/19 04:49:24 [alert] 1#1: worker process 99 exited on signal 11 (core dumped)
19-4-2017 06:49:242017/04/19 04:49:24 [notice] 1#1: start worker process 108
19-4-2017 06:49:242017/04/19 04:49:24 [notice] 108#108: signal 17 (SIGCHLD) received
19-4-2017 06:49:242017/04/19 04:49:24 [info] 108#108: waitpid() failed (10: No child processes)
19-4-2017 06:49:242017/04/19 04:49:24 [notice] 108#108: signal 17 (SIGCHLD) received
19-4-2017 06:49:242017/04/19 04:49:24 [info] 108#108: waitpid() failed (10: No child processes)
19-4-2017 06:49:242017/04/19 04:49:24 [notice] 108#108: signal 17 (SIGCHLD) received
19-4-2017 06:49:242017/04/19 04:49:24 [info] 108#108: waitpid() failed (10: No child processes)
19-4-2017 06:49:242017/04/19 04:49:24 [notice] 108#108: signal 17 (SIGCHLD) received
19-4-2017 06:49:242017/04/19 04:49:24 [info] 108#108: waitpid() failed (10: No child processes)
```

**Comment by mikz** [comment]
So I have WIP example that actually tries to request the certificate. 

Unfortunately it fails on: `ERROR: Problem connecting to server (get for https://acme-v01.api.letsencrypt.org/directory; curl returned with 27)` which is supposed to be out of memory error.

You can check it out: https://github.com/3scale/apicast/compare/example-autossl

**Comment by ErwinSteffens** [comment]
Ok, thanks, I will check it out.
